name: "Gtag"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    
jobs:
  gtag:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: HappyPathway/centralized-actions/.github/workflows/gtag.yml@main
    with:
      patch: true
      github_org: ${{ vars.GH_ORG }}
      github_username: ${{ vars.GH_USERNAME }}
      github_email: ${{ vars.GH_EMAIL }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
